name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU (optional, for multi-platform builds)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx (optional, for multi-platform builds)
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        echo "Building image with tag my-image-name:${{ github.sha }}"
        docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}

    - name: Tag the Docker image as latest
      if: github.event_name == 'push'
      run: |
        docker tag my-image-name:${{ github.sha }} my-image-name:latest

    - name: Push the Docker image
      if: github.event_name == 'push'
      run: |
        echo "Pushing image my-image-name:${{ github.sha }}"
        docker push my-image-name:${{ github.sha }}
        echo "Pushing image my-image-name:latest"
        docker push my-image-name:latest

    - name: Post job cleanup
      if: always()
      run: |
        echo "Cleaning up..."
        # 添加任何必要的清理命令
