name: Docker Image CI

on:
  push:
    branches:
      - main  # 主分支推送会触发构建
  pull_request:
    branches:
      - main  # 向主分支发起的拉取请求也会触发构建

jobs:
  build:
    runs-on: ubuntu-22.04  # 指定使用 Ubuntu 22.04

    steps:
      - name: Checkout repository  # 第一步：检出仓库代码
        uses: actions/checkout@v3  # 使用官方提供的 checkout action 来获取代码库内容

      - name: Log in to Docker Hub  # 第二步：登录 Docker Hub
        uses: docker/login-action@v2  # 使用官方提供的 login action 进行 Docker Hub 登录
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 从 GitHub Secrets 获取 Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 从 GitHub Secrets 获取 Docker Hub 密码

      - name: Set up QEMU  # 第三步：设置 QEMU（用于多平台构建，可选）
        uses: docker/setup-qemu-action@v2  # 使用官方提供的 setup-qemu action 设置 QEMU

      - name: Print Git SHA and Docker Username  # 打印 Git 提交 SHA 和 Docker 用户名，用于调试
        run: |
          echo "Git SHA: ${{ github.sha }}"
          echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"

      - name: Build the Docker image  # 第五步：构建 Docker 镜像
        run: |
          local_sha=${{ github.sha }}
          echo "Building image with tag oops-icons:${local_sha}"
          docker build --tag oops-icons:${local_sha} .

      - name: List Docker images  # 列出当前可用的 Docker 镜像，用于调试
        run: docker images

      - name: Tag the Docker image  # 第六步：给 Docker 镜像打标签
        run: |
          local_sha=${{ github.sha }}
          echo "Tagging image oops-icons:${local_sha} as ${DOCKER_USERNAME}/oops-icons:${local_sha}"
          docker tag oops-icons:${local_sha} ${DOCKER_USERNAME}/oops-icons:${local_sha}
          echo "Tagging image oops-icons:${local_sha} as ${DOCKER_USERNAME}/oops-icons:latest"
          docker tag oops-icons:${local_sha} ${DOCKER_USERNAME}/oops-icons:latest

      - name: Push the Docker image  # 第七步：推送 Docker 镜像到 Docker Hub
        run: |
          local_sha=${{ github.sha }}
          echo "Pushing image ${DOCKER_USERNAME}/oops-icons:${local_sha}"
          docker push ${DOCKER_USERNAME}/oops-icons:${local_sha}
          echo "Pushing image ${DOCKER_USERNAME}/oops-icons:latest"
          docker push ${DOCKER_USERNAME}/oops-icons:latest
